defaults:
  - _self_
  - data_loader

data_processor:
  output_path: data/processed/processed_data.csv

  min_iv: 0.005
  max_iv: 3.0
  moneyness_min: 0.5
  moneyness_max: 1.5
  min_open_interest: 100.0
  risk_free_rate: 0.0
  dividend_yield: 0.0
  days_in_year: 365.0