f_variance:
  output_path: "data/forward_variance/forward_variance_data.csv"

iv_surface:
  surface_path: "data/iv_surface/iv_surface.npy"
  maturities_path: "data/iv_surface/grid_maturities.npy"
  log_moneyness_path: "data/iv_surface/grid_log_moneyness.npy"
  risk_free_rate_path: "data/iv_surface/grid_risk_free_rates.npy"

rbergomi:
  save_path: "data/rbergomi_model"

seed: 42  # Random seed for reproducibility

calibration:
  n_paths: 65536  # Number of Monte Carlo paths for calibration
  n_steps: 1024    # Number of time steps for calibration
  regularisation_weight: 0.0005  # Weight for regularization term in calibration objective
  maturities_filter: 0.01  # Minimum maturity to consider in calibration (in years)