f_variance:
  output_path: "data/forward_variance/forward_variance_data.csv"

iv_surface:
  surface_path: "data/iv_surface/iv_surface.npy"
  maturities_path: "data/iv_surface/grid_maturities.npy"
  log_moneyness_path: "data/iv_surface/grid_log_moneyness.npy"
  risk_free_rate_path: "data/iv_surface/grid_risk_free_rates.npy"

rbergomi:
  save_path: "data/rbergomi_model"
