defaults:
  - data_loader
  - data_processor

data_loader:
  sql_query: "scripts/validation_data_query.sql"
  output_path: "data/raw/TSLA_val_data.csv"

data_processor:
  output_path: "data/processed/processed_validation_data.csv"